### ISSUE TITLE
[Feat] : 11/11 회의 수정  

### ISSUE THREAD

**Issue by Ryeolee** [Mojacknong/Farmus-msa-user#23]
## ✏️ Description

11/11 회의 후 수정 할 것들
난이도 로직 변경
동기, 태그 db 수정
회원가입 프로필 가져오지 않기, 중복 함수 제거 
프로필 사진 null 문제 해결

## To-Do List

- [ ]  난이도 로직 변경
- [ ]  동기, 태그 db 수정
- [ ] 회원가입 프로필 가져오지 않기, 중복 함수 제거
- [ ] 프로필 사진 null 문제 해결
